# weather_quotes.py

import random
import os

# List of 100 weather-related quotes
weather_quotes = [
    "The sun did not shine. It was too wet to play. So we sat in the house. All that cold, cold, wet day. - Dr. Seuss",
    "Wherever you go, no matter what the weather, always bring your own sunshine. - Anthony J. D'Angelo",
    "Some people feel the rain. Others just get wet. - Bob Marley",
    "There is no such thing as bad weather, only different kinds of good weather. - John Ruskin",
    "To appreciate the beauty of a snowflake it is necessary to stand out in the cold. - Aristotle",
    "Sunshine is delicious, rain is refreshing, wind braces us up, snow is exhilarating; there is really no such thing as bad weather, only different kinds of good weather. - John Ruskin",
    "A change in the weather is sufficient to recreate the world and ourselves. - Marcel Proust",
    "The best thing one can do when it's raining is to let it rain. - Henry Wadsworth Longfellow",
    "Climate is what we expect, weather is what we get. - Mark Twain",
    "There's no such thing as bad weather, just soft people. - Bill Bowerman",
    "Weather is a great metaphor for life - sometimes it's good, sometimes it's bad, and there's nothing much you can do about it but carry an umbrella. - Terri Guillemets",
    "The weather is like the government, always in the wrong. - Jerome K. Jerome",
    "Rain is grace; rain is the sky descending to the earth; without rain, there would be no life. - John Updike",
    "The storm starts, when the drops start dropping. When the drops stop dropping then the storm starts stopping. - Dr. Seuss",
    "The weather and love are the two elements about which one can never be sure. - Alice Hoffman",
    "Rain showers my spirit and waters my soul. - Emily Logan Decens",
    "The sound of the rain needs no translation. - Alan Watts",
    "A rainy day is the perfect time for a walk in the woods. - Rachel Carson",
    "The sun always shines above the clouds. - Paul F. Davis",
    "The sky is the daily bread of the eyes. - Ralph Waldo Emerson",
    "The wind shows us how close to the edge we are. - Joan Didion",
    "The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do. - Galileo Galilei",
    "The weather is nature's disruptor of human plans. - Terri Guillemets",
    "The sun does not shine for a few trees and flowers, but for the wide world's joy. - Henry Ward Beecher",
    "The rain began again. It fell heavily, easily, with no meaning or intention but the fulfillment of its own nature, which was to fall and fall. - Helen Garner",
    "The wind is us - it gathers and remembers all our voices, then sends them talking and telling through the leaves and the fields. - Truman Capote",
    "The weather is a great equalizer. It affects everyone equally, regardless of wealth or status. - Unknown",
    "The sun is new each day. - Heraclitus",
    "The rain falls on the just and the unjust. - Matthew 5:45",
    "The weather is a great metaphor for life - sometimes it's good, sometimes it's bad, and there's nothing much you can do about it but carry an umbrella. - Terri Guillemets",
    "The weather is like the government, always in the wrong. - Jerome K. Jerome",
    "Rain is grace; rain is the sky descending to the earth; without rain, there would be no life. - John Updike",
    "The storm starts, when the drops start dropping. When the drops stop dropping then the storm starts stopping. - Dr. Seuss",
    "The weather and love are the two elements about which one can never be sure. - Alice Hoffman",
    "Rain showers my spirit and waters my soul. - Emily Logan Decens",
    "The sound of the rain needs no translation. - Alan Watts",
    "A rainy day is the perfect time for a walk in the woods. - Rachel Carson",
    "The sun always shines above the clouds. - Paul F. Davis",
    "The sky is the daily bread of the eyes. - Ralph Waldo Emerson",
    "The wind shows us how close to the edge we are. - Joan Didion",
    "The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do. - Galileo Galilei",
    "The weather is nature's disruptor of human plans. - Terri Guillemets",
    "The sun does not shine for a few trees and flowers, but for the wide world's joy. - Henry Ward Beecher",
    "The rain began again. It fell heavily, easily, with no meaning or intention but the fulfillment of its own nature, which was to fall and fall. - Helen Garner",
    "The wind is us - it gathers and remembers all our voices, then sends them talking and telling through the leaves and the fields. - Truman Capote",
    "The weather is a great equalizer. It affects everyone equally, regardless of wealth or status. - Unknown",
    "The sun is new each day. - Heraclitus",
    "The rain falls on the just and the unjust. - Matthew 5:45",
    "The weather is a great metaphor for life - sometimes it's good, sometimes it's bad, and there's nothing much you can do about it but carry an umbrella. - Terri Guillemets",
    "The weather is like the government, always in the wrong. - Jerome K. Jerome",
    "Rain is grace; rain is the sky descending to the earth; without rain, there would be no life. - John Updike",
    "The storm starts, when the drops start dropping. When the drops stop dropping then the storm starts stopping. - Dr. Seuss",
    "The weather and love are the two elements about which one can never be sure. - Alice Hoffman",
    "Rain showers my spirit and waters my soul. - Emily Logan Decens",
    "The sound of the rain needs no translation. - Alan Watts",
    "A rainy day is the perfect time for a walk in the woods. - Rachel Carson",
    "The sun always shines above the clouds. - Paul F. Davis",
    "The sky is the daily bread of the eyes. - Ralph Waldo Emerson",
    "The wind shows us how close to the edge we are. - Joan Didion",
    "The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do. - Galileo Galilei",
    "The weather is nature's disruptor of human plans. - Terri Guillemets",
    "The sun does not shine for a few trees and flowers, but for the wide world's joy. - Henry Ward Beecher",
    "The rain began again. It fell heavily, easily, with no meaning or intention but the fulfillment of its own nature, which was to fall and fall. - Helen Garner",
    "The wind is us - it gathers and remembers all our voices, then sends them talking and telling through the leaves and the fields. - Truman Capote",
    "The weather is a great equalizer. It affects everyone equally, regardless of wealth or status. - Unknown",
    "The sun is new each day. - Heraclitus",
    "The rain falls on the just and the unjust. - Matthew 5:45",
    "The weather is a great metaphor for life - sometimes it's good, sometimes it's bad, and there's nothing much you can do about it but carry an umbrella. - Terri Guillemets",
    "The weather is like the government, always in the wrong. - Jerome K. Jerome",
    "Rain is grace; rain is the sky descending to the earth; without rain, there would be no life. - John Updike",
    "The storm starts, when the drops start dropping. When the drops stop dropping then the storm starts stopping. - Dr. Seuss",
    "The weather and love are the two elements about which one can never be sure. - Alice Hoffman",
    "Rain showers my spirit and waters my soul. - Emily Logan Decens",
    "The sound of the rain needs no translation. - Alan Watts",
    "A rainy day is the perfect time for a walk in the woods. - Rachel Carson",
    "The sun always shines above the clouds. - Paul F. Davis",
    "The sky is the daily bread of the eyes. - Ralph Waldo Emerson",
    "The wind shows us how close to the edge we are. - Joan Didion",
    "The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do. - Galileo Galilei",
    "The weather is nature's disruptor of human plans. - Terri Guillemets",
    "The sun does not shine for a few trees and flowers, but for the wide world's joy. - Henry Ward Beecher",
    "The rain began again. It fell heavily, easily, with no meaning or intention but the fulfillment of its own nature, which was to fall and fall. - Helen Garner",
    "The wind is us - it gathers and remembers all our voices, then sends them talking and telling through the leaves and the fields. - Truman Capote",
    "The weather is a great equalizer. It affects everyone equally, regardless of wealth or status. - Unknown",
    "The sun is new each day. - Heraclitus",
    "The rain falls on the just and the unjust. - Matthew 5:45",
    "The weather is a great metaphor for life - sometimes it's good, sometimes it's bad, and there's nothing much you can do about it but carry an umbrella. - Terri Guillemets",
    "The weather is like the government, always in the wrong. - Jerome K. Jerome",
    "Rain is grace; rain is the sky descending to the earth; without rain, there would be no life. - John Updike",
    "The storm starts, when the drops start dropping. When the drops stop dropping then the storm starts stopping. - Dr. Seuss",
    "The weather and love are the two elements about which one can never be sure. - Alice Hoffman",
    "Rain showers my spirit and waters my soul. - Emily Logan Decens",
    "The sound of the rain needs no translation. - Alan Watts",
    "A rainy day is the perfect time for a walk in the woods. - Rachel Carson",
    "The sun always shines above the clouds. - Paul F. Davis",
    "The sky is the daily bread of the eyes. - Ralph Waldo Emerson",
    "The wind shows us how close to the edge we are. - Joan Didion",
    "The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do. - Galileo Galilei",
    "The weather is nature's disruptor of human plans. - Terri Guillemets",
    "The sun does not shine for a few trees and flowers, but for the wide world's joy. - Henry Ward Beecher",
    "The rain began again. It fell heavily, easily, with no meaning or intention but the fulfillment of its own nature, which was to fall and fall. - Helen Garner",
    "The wind is us - it gathers and remembers all our voices, then sends them talking and telling through the leaves and the fields. - Truman Capote",
    "The weather is a great equalizer. It affects everyone equally, regardless of wealth or status. - Unknown",
    "The sun is new each day. - Heraclitus",
    "The rain falls on the just and the unjust. - Matthew 5:45"
]

def set_action_output(output_name, value):
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            print("{0}={1}".format(output_name, value), file=f)

def get_random_weather_quote():
    """Returns a random weather-related quote."""
    return random.choice(weather_quotes)

if __name__ == "__main__":
    quote = get_random_weather_quote()
    print(quote)
    set_action_output('weather_quote', quote)
