name: Test replace variables

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
  release:
    types: [published]
#  schedule:
    #- cron: '10 * * * *'  # Runs every hour at minute 10
#    - cron: '10 6-20 * * *'  # At minute 10 past every hour from 6 through 20
concurrency:
  group: generate-json-files
  
jobs:
  replace-variables:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz
    - name: Run replace_variables script
      env:
        TEMPLATE_PATH: 'README_template.md'
        OUTPUT_PATH: 'README.md'
        CITY: 'Lisbon'
        COUNTRY: 'Portugal'
        WEATHER_CODE: ${{ 1 }}
        RAIN_FORECAST: ${{ 20 }}
        RAIN_PROBABILITY:  ${{ 5 }}
        HOUR_NOW: ${{ 12 }}
        # Add more environment variables as needed
      run: python replace_variables.py
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull --all
        git add -A
        git commit -m 'Add generated readme file'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
#  send-hourly-weather-consumer:
#    runs-on: ubuntu-latest
#    needs:
#      - run-hourly-weather-consumer
#    if: needs.run-hourly-weather-consumer.outputs.rain != 'No rain' 
#    steps:
#    - name: Current weather - Notify twitter
#      uses: nearform-actions/github-action-notify-twitter@master
#      with:
#        message: |
#          needs.run-hourly-weather-consumer.outputs.tweet_1
#          needs.run-hourly-weather-consumer.outputs.tweet_2
#          needs.run-hourly-weather-consumer.outputs.tweet_3
#        twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
#        twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
#        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

        
        
    
        
