name: Weather Consumer

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 07

jobs:
  run-weather-consumer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install openmeteo-requests
        pip install requests-cache retry-requests numpy pandas

    - name: Run weather consumer script
      id: weather
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        OPENWEATHER_API_CITY: ${{ vars.CITY }}
      run: |
        python weather_consumer.py

    - name: Run weather forecast script
      id: forecast
      env:
        OPEN_METEO_CITY_LAT: ${{ vars.OPEN_METEO_CITY_LAT }}
        OPEN_METEO_CITY_LONG: ${{ vars.OPEN_METEO_CITY_LONG }}
      run: |
        python weather_forecast.py

    - name: Run quote of the day script
      id: quote
      run: |
        python weather_quotes.py

    - name: Display forecast data
      run: |
        echo "Weather in ${{ vars.CITY }}: ${{ steps.weather.outputs.weather_description }}" 
        echo "Temperature: ${{ steps.weather.outputs.temperature }}Cº"
        echo "Min. temperature: ${{ steps.weather.outputs.temp_min }}Cº"
        echo "Max. temperature: ${{ steps.weather.outputs.temp_max }}Cº"
        echo "Wind speed: ${{ steps.weather.outputs.wind_speed }} meter/sec"
        echo "Wind speed: ${{ steps.weather.outputs.wind_kmph }} km/h"
        echo "Wind direction: ${{ steps.weather.outputs.wind_deg }}º"
        echo "Weather for ${{ steps.forecast.outputs.weather_forecast_date_0 }}: Max. temperature: ${{ steps.forecast.outputs.weather_forecast_max_0 }} Cº"
        echo "Weather for Min. temperature: ${{ steps.forecast.outputs.weather_forecast_min_0 }} Cº"

    - name: Quote of the day - Notify twitter
      uses: nearform-actions/github-action-notify-twitter@master
      with:
        message: |
          Quote of the day 💬💭:
          ${{ steps.quote.outputs.weather_quote }}.
        twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        
    - name: Current weather - Notify twitter
      uses: nearform-actions/github-action-notify-twitter@master
      with:
        message: |
          Weather in ${{ vars.CITY }}: ${{ steps.weather.outputs.weather_description }}
          Temperature: ${{ steps.weather.outputs.temperature }} Cº / Min.: ${{ steps.weather.outputs.temp_min }} Cº / Max.: ${{ steps.weather.outputs.temp_max }} Cº
          ${{ steps.forecast.outputs.weather_forecast_rain_0 }}
          Wind speed: ${{ steps.weather.outputs.wind_speed }} meters/sec => ${{ steps.weather.outputs.wind_kmph }} km/h 
          Wind direction: ${{ steps.weather.outputs.wind_deg }}º
        twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    - name: Forecast weather - Notify twitter
      uses: nearform-actions/github-action-notify-twitter@master
      with:
        message: |
          Forecast for ${{ vars.CITY }}:
          ${{ steps.forecast.outputs.weather_forecast_date_1 }}:
          Max. temp: ${{ steps.forecast.outputs.weather_forecast_max_1 }} Cº Min.: ${{ steps.forecast.outputs.weather_forecast_min_1 }} Cº ${{ steps.forecast.outputs.weather_forecast_rain_1 }} ${{ steps.forecast.outputs.wind_speed_10m_1 }}
          ${{ steps.forecast.outputs.weather_forecast_date_2 }}: 
          Max. temp: ${{ steps.forecast.outputs.weather_forecast_max_2 }} Cº Min.: ${{ steps.forecast.outputs.weather_forecast_min_2 }} Cº ${{ steps.forecast.outputs.weather_forecast_rain_2 }} ${{ steps.forecast.outputs.wind_speed_10m_2 }}
          ${{ steps.forecast.outputs.weather_forecast_date_3 }}: 
          Max. temp: ${{ steps.forecast.outputs.weather_forecast_max_3 }} Cº Min.: ${{ steps.forecast.outputs.weather_forecast_min_3 }} Cº ${{ steps.forecast.outputs.weather_forecast_rain_3 }} ${{ steps.forecast.outputs.wind_speed_10m_3 }}
        twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}


        
        
    
        
